-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 21:11:35 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema endereco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema endereco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `endereco` DEFAULT CHARACTER SET utf8 ;
USE `endereco` ;

-- -----------------------------------------------------
-- Table `endereco`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `endereco`.`pais` ;

CREATE TABLE IF NOT EXISTS `endereco`.`pais` (
  `idpais` INT NOT NULL AUTO_INCREMENT,
  `nome_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpais`),
  UNIQUE INDEX `idpais_UNIQUE` (`idpais` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereco`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `endereco`.`estado` ;

CREATE TABLE IF NOT EXISTS `endereco`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nome_estado` VARCHAR(45) NOT NULL,
  `idpais` INT NOT NULL,
  PRIMARY KEY (`idestado`),
  UNIQUE INDEX `idestado_UNIQUE` (`idestado` ASC),
  UNIQUE INDEX `nome_estado_UNIQUE` (`nome_estado` ASC),
  INDEX `fk_estado_pais1_idx` (`idpais` ASC),
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`idpais`)
    REFERENCES `endereco`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereco`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `endereco`.`cidade` ;

CREATE TABLE IF NOT EXISTS `endereco`.`cidade` (
  `idcidade` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(45) NOT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idcidade`),
  UNIQUE INDEX `idcidade_UNIQUE` (`idcidade` ASC),
  INDEX `fk_cidade_estado1_idx` (`idestado` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`idestado`)
    REFERENCES `endereco`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereco`.`bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `endereco`.`bairro` ;

CREATE TABLE IF NOT EXISTS `endereco`.`bairro` (
  `idbairro` INT NOT NULL AUTO_INCREMENT,
  `nome_bairro` VARCHAR(45) NOT NULL,
  `idcidade` INT NOT NULL,
  PRIMARY KEY (`idbairro`),
  UNIQUE INDEX `idbairro_UNIQUE` (`idbairro` ASC),
  INDEX `fk_bairro_cidade1_idx` (`idcidade` ASC),
  CONSTRAINT `fk_bairro_cidade1`
    FOREIGN KEY (`idcidade`)
    REFERENCES `endereco`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereco`.`rua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `endereco`.`rua` ;

CREATE TABLE IF NOT EXISTS `endereco`.`rua` (
  `idrua` INT NOT NULL AUTO_INCREMENT,
  `nome_rua` VARCHAR(45) NOT NULL,
  `idbairro` INT NOT NULL,
  PRIMARY KEY (`idrua`),
  UNIQUE INDEX `idrua_UNIQUE` (`idrua` ASC),
  INDEX `fk_rua_bairro1_idx` (`idbairro` ASC),
  CONSTRAINT `fk_rua_bairro1`
    FOREIGN KEY (`idbairro`)
    REFERENCES `endereco`.`bairro` (`idbairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereco`.`cep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `endereco`.`cep` ;

CREATE TABLE IF NOT EXISTS `endereco`.`cep` (
  `cep` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`cep`),
  UNIQUE INDEX `cep_UNIQUE` (`cep` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereco`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `endereco`.`endereco` ;

CREATE TABLE IF NOT EXISTS `endereco`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `idcidade` INT NOT NULL,
  `idrua` INT NOT NULL,
  `idbairro` INT NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_endereco_cidade1_idx` (`idcidade` ASC),
  INDEX `fk_endereco_rua1_idx` (`idrua` ASC),
  INDEX `fk_endereco_bairro1_idx` (`idbairro` ASC),
  INDEX `fk_endereco_cep1_idx` (`cep` ASC),
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`idcidade`)
    REFERENCES `endereco`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_rua1`
    FOREIGN KEY (`idrua`)
    REFERENCES `endereco`.`rua` (`idrua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_bairro1`
    FOREIGN KEY (`idbairro`)
    REFERENCES `endereco`.`bairro` (`idbairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_cep1`
    FOREIGN KEY (`cep`)
    REFERENCES `endereco`.`cep` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
